[package]
name = "rg35xx-plus-toolbox"
version = "0.1.0"
authors = ["Philippe Simons"]
edition = "2018"

[dependencies]
nix = { version = "0.28.0", features = ["ioctl"] }
clap = { version = "=4.4.7", features = ["derive"] }
